### ISSUE TITLE
regarding android 

### ISSUE THREAD

**Issue by sweetyshetty08** [PrajwalaTM/Android-Projects#1]
how to start with android and proceed ..please help :(

**Comment by rishi1111** [comment]
@sweetyshetty08 May i suggest Udacity's Android Basics if you have 0 experience.

**Comment by PrajwalaTM** [comment]
I started off watching the following set of videos: 
https://www.youtube.com/watch?v=QAbQgLGKd3Y&list=PL6gx4Cwl9DGBsvRxJJOzG4r4k_zLKrnxl

Once you start coding, you'll end up understanding concepts with a greater clarity, but these should be good to help you start off. Hope it helps.

**Comment by sweetyshetty08** [comment]
Thank You 👍 :)
